#![allow(non_upper_case_globals)]
//! includes the file generated by `build.rs` containing the internal plain & compressed static files to be served


include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));